### ISSUE TITLE
Make sure no zombie processes are left

### ISSUE THREAD

**Issue by hvy** [hvy/small-shell#5]

**Comment by johnPertoft** [comment]
http://stackoverflow.com/questions/12427524/killing-child-processes-at-parent-process-exit

**Comment by johnPertoft** [comment]
Tror man kan göra kill(0, SIGTERM) eller nåt, 0 som pid går till alla i processgruppen.

"If pid is 0, sig shall be sent to all processes (excluding an unspecified set of system processes) whose process group ID is equal to the process group ID of the sender, and for which the process has permission to send a signal."
